        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     NMI
        .dw     START
