;****************************************************************
; This file is auto-generated by ddmake from startrek.toml
; *** DO NOT EDIT ***
;****************************************************************

; Start of chip memory mapping
STRTADD = 0x0000

; 2K ROM
ROMSIZE = 0x0800

; The code actually needs 4 bytes ram at this address for the command buffer.
; However, stack also starts here, and will grow down (towards 0) from this point.
; So, we need some above and below this address.  I generally choose the
; Top of RAM minus 16
RAMADDR = 0xcff0

; delay factor
BIGDEL = 0x0180

        .include "../dd/dd.def"
        .include "../dd/z80.def"
        .include "../io/romio.def"

;------- region1  -----------------------------------------------

        .bank   region1 (base=STRTADD, size=IRQADD-STRTADD)
        .area   region1 (ABS, BANK=region1)

;
;       START CODE
;
START:
        DI                  ; Disable interrupts - we don't handle them
        LD      SP,RAMADDR  ; have to set valid SP
;       YOUR SMALL CODE CAN GO HERE
        JP      START2


;------- region2  -----------------------------------------------

        .bank   region2 (base=IRQADD, size=NMIADD-IRQADD)
        .area   region2 (ABS, BANK=region2)

;
;       IRQ HANDLER
;
IRQ:
        RETI


;------- region3  -----------------------------------------------

        .bank   region3 (base=NMIADD, size=IOADD-NMIADD)
        .area   region3 (ABS, BANK=region3)

;
;       NMI HANDLER
;
NMI:
        RETN

;
;       START CODE 2
;
START2:
        LD      A,0x81
        LD      HL,0xE000
        LD      (HL),A      ; blank the screen
        JP      INIT

        .include "../dd/z80_main.asm"
;
;       EVERY CODE
;
EVERY:
;       YOUR CODE CAN GO HERE
        RET

        .include "../io/z80_romio.asm"

;------- region4  -----------------------------------------------

        .bank   region4 (base=IOADD, size=IOEND-IOADD)
        .area   region4 (ABS, BANK=region4)

        .include "../io/romio_table.asm"

;------- region5  -----------------------------------------------

        .bank   region5 (base=IOEND, size=ROMEND-IOEND)
        .area   region5 (ABS, BANK=region5)


