
[Template]
#--------------------------------------------------------------------------
# ROM TEMPLATE - this defines the rom layout, and which kind of io
#--------------------------------------------------------------------------
file = "templates/6809_romio_f800_2k.toml"