M48
; DRILL file {KiCad (6.0.0)} date Sun Mar 13 18:30:10 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-13T18:30:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X101.6Y-95.885
X101.6Y-165.1
X179.705Y-95.885
X179.705Y-165.1
T0
M30
