;****************************************************************
; This file is auto-generated by ddmake from astrocde.toml
; *** DO NOT EDIT ***
;****************************************************************

; Start of chip memory mapping
STRTADD = 0x2000

; 2K ROM
ROMSIZE = 0x0800

; The code actually needs 4 bytes ram at this address for the command buffer.
; In this case, the stack is elsewhere, set by the Astrocade BIOS
; 
RAMADDR = 0x4fce

; delay factor
BIGDEL = 0x0180

        .include "../dd/dd.def"
        .include "../dd/z80.def"
        .include "../io/romio.def"

;------- region1  -----------------------------------------------

        .bank   region1 (base=STRTADD, size=IOADD-STRTADD)
        .area   region1 (ABS, BANK=region1)

        .byte   0x55        ; cartridge header
        .word   0x0218      ; next menu item (first one)
        .word   TITLE       ; title pointer
        .word   START       ; start pointer
        
        ret                 ; rst8
        nop
        nop

        ret                 ; rst16
        nop
        nop
        
        ret                 ; rst24
        nop
        nop
        
        ret                 ; rst32
        nop
        nop
        
        ret                 ; rst40
        nop
        nop
        
        ret                 ; rst48
        nop
        nop

TITLE:
        .asciz	"DEMON DEBUGGER"

;
;       START CODE
;
START:
;
;       Assume the stack and the interrupt states are
;       set up properly, by the Astrocade BIOS.
;       Comment out normal startup code
;
        ;DI                  ; Disable interrupts - we don't handle them
        ;LD      SP,RAMADDR  ; have to set valid SP
        JP       INIT

        .include "../dd/z80_main.asm"
;
;       EVERY CODE
;
EVERY:
        IN	A,(0x10)    ; hit watchdog
        RET

        .include "../io/z80_romio.asm"

;------- region2  -----------------------------------------------

        .bank   region2 (base=IOADD, size=IOEND-IOADD)
        .area   region2 (ABS, BANK=region2)

        .include "../io/romio_table.asm"

;------- region3  -----------------------------------------------

        .bank   region3 (base=IOEND, size=ROMEND-IOEND)
        .area   region3 (ABS, BANK=region3)


